//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCBP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalFeedback
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public int LecturerId { get; set; }
        public int Feedback { get; set; }
        public int Year { get; set; }
    
        public virtual AppraisalQuestionnaire AppraisalQuestionnaire { get; set; }
        public virtual Lecturer Lecturer { get; set; }
    }
}
