//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCBP.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NCBPEntities : DbContext
    {
        public NCBPEntities()
            : base("name=NCBPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppraisalFeedback> AppraisalFeedbacks { get; set; }
        public virtual DbSet<AppraisalQuestionnaire> AppraisalQuestionnaires { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CurriculumFeedback> CurriculumFeedbacks { get; set; }
        public virtual DbSet<CurriculumQuestionnaire> CurriculumQuestionnaires { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Entitlement> Entitlements { get; set; }
        public virtual DbSet<Lecturer> Lecturers { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<PreviousExamInfo> PreviousExamInfoes { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<StudentProfile> StudentProfiles { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
