//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCBP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public int Id { get; set; }
        public System.Guid StudentId { get; set; }
        public int SemesterNo { get; set; }
        public string Result { get; set; }
    
        public virtual StudentProfile StudentProfile { get; set; }
    }
}
